# Generated by Django 5.2.4 on 2025-07-13 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المصور')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مصور',
                'verbose_name_plural': 'المصورون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotographyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الباقة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الافتراضي')),
                ('num_photos_digital', models.IntegerField(default=0, verbose_name='عدد الصور الرقمية')),
                ('num_photos_printed', models.IntegerField(default=0, verbose_name='عدد الصور المطبوعة')),
                ('includes_album', models.BooleanField(default=False, verbose_name='يتضمن ألبوم')),
                ('includes_frame', models.BooleanField(default=False, verbose_name='يتضمن إطار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'باقة تصوير',
                'verbose_name_plural': 'باقات التصوير',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم الجلسة')),
                ('session_date', models.DateField(verbose_name='تاريخ الجلسة')),
                ('session_time', models.TimeField(blank=True, null=True, verbose_name='وقت الجلسة')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الكلي للجلسة')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('processing', 'قيد المعالجة'), ('ready_for_delivery', 'جاهزة للتسليم'), ('delivered', 'تم التسليم'), ('partially_paid', 'مدفوعة جزئياً')], default='scheduled', max_length=30, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الجلسة')),
                ('digital_photos_delivered', models.BooleanField(default=False, verbose_name='تم تسليم الصور الرقمية')),
                ('printed_photos_delivered', models.BooleanField(default=False, verbose_name='تم تسليم الصور المطبوعة')),
                ('album_delivered', models.BooleanField(default=False, verbose_name='تم تسليم الألبوم')),
                ('frame_delivered', models.BooleanField(default=False, verbose_name='تم تسليم الإطار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sessions', to='print.client', verbose_name='العميل')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صدر عن')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_sessions', to='print.photographypackage', verbose_name='الباقة')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='print.photographer', verbose_name='المصور المعين')),
            ],
            options={
                'verbose_name': 'جلسة تصوير',
                'verbose_name_plural': 'جلسات التصوير',
                'ordering': ['-session_date', '-session_time'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم الإيصال')),
                ('print_type', models.CharField(choices=[('album', 'ألبوم'), ('wood_tablo', 'تابلو خشب'), ('canvas', 'كانفاس'), ('frame', 'إطار'), ('photo_paper', 'ورق صور'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الطباعة')),
                ('size', models.CharField(blank=True, choices=[('small_album', 'ألبوم صغير (20x20)'), ('large_album', 'ألبوم كبير (30x30)'), ('30x40', '30×40 سم'), ('40x60', '40×60 سم'), ('50x70', '50×70 سم'), ('60x90', '60×90 سم'), ('A4', 'A4'), ('A3', 'A3'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='الحجم')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الكلي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('partially_paid', 'مدفوع جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='print.client', verbose_name='العميل')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صدر عن')),
            ],
            options={
                'verbose_name': 'طلب طباعة',
                'verbose_name_plural': 'طلبات الطباعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم الإيصال')),
                ('receipt_type', models.CharField(choices=[('printing', 'طباعة'), ('photography', 'تصوير'), ('booking', 'حجز')], max_length=20, verbose_name='نوع الإيصال')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي للإيصال')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع في هذه الدفعة')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('mobile_money', 'دفع إلكتروني'), ('card', 'بطاقة ائتمان/خصم')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإيصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صدر عن')),
                ('printing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='print.printjob', verbose_name='طلب الطباعة')),
            ],
            options={
                'verbose_name': 'إيصال دفع',
                'verbose_name_plural': 'إيصالات الدفع',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدير'), ('employee', 'موظف')], default='employee', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
