# Generated by Django 5.2.4 on 2025-07-16 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'العميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['name'], 'verbose_name': 'المصور', 'verbose_name_plural': 'المصورون'},
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='photography_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='print.photosession', verbose_name='جلسة التصوير'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='photographypackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL, verbose_name='صدر عن'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع فعلياً'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('mobile_money', 'دفع إلكتروني'), ('card', 'بطاقة ائتمان/خصم'), ('other', 'أخرى')], max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='print.printjob', verbose_name='طلب الطباعة'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الإيصال'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('printing', 'طباعة'), ('photography', 'تصوير')], max_length=20, verbose_name='نوع الإيصال'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الكلي للدفعة'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='num_photos_digital',
            field=models.IntegerField(default=0, verbose_name='عدد الصور الرقمية المضمنة'),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='num_photos_printed',
            field=models.IntegerField(default=0, verbose_name='عدد الصور المطبوعة المضمنة'),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='photographypackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_photo_sessions', to=settings.AUTH_USER_MODEL, verbose_name='صدر عن'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='print.photographypackage', verbose_name='الباقة'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم إيصال الجلسة'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدولة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة'), ('processing', 'قيد المعالجة'), ('ready_for_delivery', 'جاهزة للتسليم'), ('partially_paid', 'مدفوعة جزئياً')], default='scheduled', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسليم المتوقع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printjob',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_print_jobs', to=settings.AUTH_USER_MODEL, verbose_name='صدر عن'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='print_type',
            field=models.CharField(choices=[('digital', 'طباعة رقمية'), ('offset', 'طباعة أوفست'), ('large_format', 'طباعة كبيرة الحجم'), ('screen_printing', 'طباعة سلك سكرين'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الطباعة'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الإيصال'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('custom', 'مقاس خاص')], default=django.utils.timezone.now, max_length=50, verbose_name='المقاس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('ready_for_delivery', 'جاهزة للتسليم'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة'), ('partially_paid', 'مدفوعة جزئياً')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('alert_type', models.CharField(choices=[('low_stock', 'نقص مخزون'), ('overdue_payment', 'دفعة متأخرة'), ('new_job', 'طلب جديد'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='نوع التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'تنبيهات',
                'ordering': ['-created_at'],
            },
        ),
    ]
