# Generated by Django 5.2.4 on 2025-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_alter_client_options_alter_photographer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='agreement_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الاتفاقية'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='editing_status',
            field=models.CharField(choices=[('not_started', 'لم تبدأ'), ('in_shooting', 'قيد التصوير'), ('in_editing', 'قيد التعديل'), ('in_printing', 'قيد الطباعة'), ('completed', 'تم الانتهاء')], default='not_started', max_length=20, verbose_name='حالة التعديل/المعالجة'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'زفاف'), ('portrait', 'بورتريه'), ('product', 'منتجات'), ('event', 'فعالية'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='نوع الحدث/التصوير'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='final_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم النهائي'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='final_gallery_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='رابط المعرض النهائي'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='num_digital_photos_delivered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الصور الرقمية المسلمة'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='num_printed_photos_delivered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الصور المطبوعة المسلمة'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='photo_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم مسلسل الصورة'),
        ),
    ]
