# Generated by Django 5.2.4 on 2025-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_photosession_agreement_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدولة'), ('in_shooting', 'قيد التصوير'), ('in_editing', 'تحت التعديل'), ('in_printing', 'قيد الطباعة'), ('ready_for_delivery', 'جاهزة للتسليم'), ('delivered', 'تم التسليم')], default='scheduled', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'مجدولة'), ('in_printing', 'قيد الطباعة'), ('in_packaging', 'قيد التغليف'), ('ready_for_delivery', 'جاهزة للتسليم'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
