# Generated by Django 5.2.4 on 2025-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0004_alter_photosession_status_alter_printjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosession',
            name='editing_status',
        ),
        migrations.AddField(
            model_name='photosession',
            name='financial_status',
            field=models.CharField(choices=[('incomplete', 'غير مكتملة'), ('completed', 'مكتملة')], default='incomplete', max_length=20, verbose_name='الحالة المالية'),
        ),
    ]
