# Generated by Django 5.2.4 on 2025-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_remove_photosession_editing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='financial_status',
            field=models.CharField(choices=[('incomplete', 'غير مكتملة'), ('completed', 'مكتملة')], default='incomplete', max_length=20, verbose_name='الحالة المالية'),
        ),
    ]
