# Generated by Django 5.2.4 on 2025-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_role_remove_profile_role_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosession',
            name='final_gallery_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط المعرض النهائي'),
        ),
    ]
