# Generated by Django 5.2.4 on 2025-07-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_alter_photosession_final_gallery_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_user_list', 'Can view list of all users'), ('add_user', 'Can add new users'), ('change_user_roles', 'Can change user roles'), ('delete_user', 'Can delete users')], 'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'ملفات شخصية'},
        ),
    ]
