# Generated by Django 5.2.4 on 2025-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='print.role', verbose_name='الأدوار المستهدفة'),
        ),
    ]
