# Generated by Django 5.2.4 on 2025-07-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0010_alert_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosession',
            options={'ordering': ['-session_date', '-session_time'], 'permissions': [('change_session_schedule', 'Can change photo session date and time'), ('assign_session_photographer', 'Can assign photographer to a session'), ('process_session_payments', 'Can process payments for photo sessions')], 'verbose_name': 'جلسة تصوير', 'verbose_name_plural': 'جلسات التصوير'},
        ),
        migrations.AlterModelOptions(
            name='printjob',
            options={'ordering': ['-created_at'], 'permissions': [('process_print_job_payments', 'Can process payments for print jobs')], 'verbose_name': 'طلب طباعة', 'verbose_name_plural': 'طلبات الطباعة'},
        ),
    ]
