# Generated by Django 5.2.4 on 2025-08-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='print_type',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='size',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='printjob',
            name='design_file_info',
            field=models.TextField(blank=True, null=True, verbose_name='معلومات ملف التصميم'),
        ),
        migrations.CreateModel(
            name='PrintJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('print_type', models.CharField(choices=[('digital', 'طباعة رقمية'), ('offset', 'طباعة أوفست'), ('large_format', 'طباعة كبيرة الحجم'), ('screen_printing', 'طباعة سلك سكرين'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الطباعة')),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('custom', 'مقاس خاص')], max_length=50, verbose_name='المقاس')),
                ('material', models.CharField(blank=True, choices=[('paper', 'ورق'), ('cardboard', 'كرتون'), ('vinyl', 'فينيل'), ('fabric', 'قماش'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='الخامة')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات العنصر')),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='print.printjob', verbose_name='طلب الطباعة')),
            ],
            options={
                'verbose_name': 'عنصر طلب طباعة',
                'verbose_name_plural': 'عناصر طلبات الطباعة',
            },
        ),
    ]
