# Generated by Django 5.2.4 on 2025-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0013_remove_printjob_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='design_file_info',
            field=models.TextField(blank=True, null=True, verbose_name='معلومات ملف التصميم'),
        ),
    ]
