"""
Django settings for stapi project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q95bm9x0&l7x6^1vhjn3ky69%hgjwiq5tz)d2-xst-l)a@h1nt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'print',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_weasyprint',
    'django_filters',
    'drf_yasg',
    'corsheaders',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # <--- هذا هو عنوان تطبيق React الافتراضي
    "http://127.0.0.1:3000", # <--- قد تحتاج هذا أيضًا
    #"http://169.254.146.83:3000", # <--- قد تحتاج هذا أيضًا
    # أضف أي نطاقات أخرى ستستخدمها الواجهة الأمامية في المستقبل
]
# أو (فقط للتطوير، ليس للإنتاج!)
#CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# إعدادات Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # <--- المصادقة بالتوكن (موصى بها للـ API)
        'rest_framework.authentication.SessionAuthentication', # <--- للمتصفحات (للوصول إلى واجهة DRF)
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # <--- يتطلب مصادقة لجميع الـ APIs افتراضياً
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        # هذه هي الـ renderers التي تسمح بتوليد PDF
        #'drf_weasyprint.renderers.WeasyPrintHTMLRenderer', # <--- هذا هو الصحيح
        #'drf_weasyprint.renderers.WeasyPrintPDFRenderer',   # <--- وهذا هو الصحيح
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, # عدد العناصر الافتراضي في كل صفحة للـ API
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend', # لتفعيل الفلترة
        'rest_framework.filters.SearchFilter', # لتفعيل البحث
        'rest_framework.filters.OrderingFilter', # لتفعيل الترتيب
    ]
}

# إعدادات لملفات Static
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # <--- مجلد تجميع الـ static files في الإنتاج
# STATICFILES_DIRS هو المكان الذي تبحث فيه Django عن ملفات static إضافية
STATICFILES_DIRS = [
    BASE_DIR / 'print' / 'static', # <--- مجلد static لتطبيقك
]

# معلومات الشركة (يمكنك تعديلها حسب الحاجة)
COMPANY_INFO = {
    'NAME': 'استوديو الإبداع',
    'ADDRESS': 'شارع الفن، حي الألوان، مدينة الخيال',
    'PHONE': '0123456789',
    'EMAIL': 'info@creative-studio.com',
    'WEBSITE': 'www.creative-studio.com',
    'LOGO_PATH': 'images/logo.png', # <--- المسار النسبي داخل مجلد static/images
}

# إعدادات اللغة والمنطقة الزمنية
LANGUAGE_CODE = 'ar' # <--- لغة المشروع
TIME_ZONE = 'Asia/Riyadh' # <--- المنطقة الزمنية المناسبة (مثال: الرياض)
USE_I18N = True
USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
